#! /bin/sh
### BEGIN INIT INFO
# Provides: noip
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: noip server
# Description:
### END INIT INFO
 
case "$1" in
    start)
        echo "noip wird gestartet"
        # Starte Programm
        sudo PYTHONPATH=".:build/lib.linux-armv7l-2.7" python /home/pi/rpi_ws281x/python/examples/LedLightStrips.py
        ;;
    stop)
        echo "noip wird beendet"
        # Beende Programm
        killall noip2
        ;;
    *)
        echo "Benutzt: /etc/init.d/noip {start|stop}"
        exit 1
        ;;
esac
 
exit 0

